version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: multi-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - multi-agent-network

  multi-agent:
    build: .
    container_name: multi-agent-app
    ports:
      - "8000:8000"
      - "3001:3001"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - A2A_SERVER_HOST=0.0.0.0
      - A2A_SERVER_PORT=8000
      - MCP_SERVER_PORT=3001
    depends_on:
      - redis
    networks:
      - multi-agent-network
    command: python src/main.py

volumes:
  redis_data:

networks:
  multi-agent-network:
    driver: bridge